version: '3'
services:
  synergy:
    image: debian
    build: ./synergy
    container_name: synergyhl2
    restart: always
    environment:
      - STEAM_USER_NAME
      - STEAM_PASSWORD
      - STEAM_GUARD
      - SERVER_NAME
      - SERVER_PASSWORD
      - SERVER_SLOTS
      - VNC_PASSWORD
    volumes:
      - "./servers:/root/Steam/"
    ports:
      - "27015:27015"
      - '27015:27015/udp'
      - '27016:27016/udp'
      - "5900:5900"
